### ISSUE TITLE
Create a double column layout

### ISSUE THREAD

**Issue by dzwiener** [AugustanaCSC490Spring2021/sandpiper-repo#15]
I am having trouble creating a two column layout that we have on our storyboard. I need to find if there is a container or way to display our elements side by side in 1 row.

**Comment by msetlock** [comment]
I'm also having this issue, from what I've seen it doesn't seem like Native Base has an easy solution. I've found a few resources I can share later that might have a workaround

**Comment by dzwiener** [comment]
We might have to look at it as a different element than a button, or wrap the buttons in a bigger layout scheme. I am looking at cards and they seem to have a lot more rendering options that aren't available in buttons. Maybe a card with a button in it?

**Comment by dzwiener** [comment]
Also native base have a grid component that can be used to create the layout I believe we want.

**Comment by msetlock** [comment]
This was something I was going to bring up! I think this might be what's needed, I'm going to try to implement it into my code tomorrow

**Comment by msetlock** [comment]
Grids can be added like so, wrapped under content and container. Items can be added to different column tags to separate them.
<Container style={styles.container}>
        <Content padder style={styles.content}>
          <Grid>
            <Col style={styles.leftContent}>
            <Button style={styles.textBlock}>
            <Text style={styles.text}>
              911 {'\n'}
            </Text>
          </Button>
          <Button style={styles.textBlock}>
            <Text style={styles.text}>
              Public Safety{'\n'}
              309-794-7000
            </Text>

          </Button>
          <Button style={styles.textBlock}>
            <Text style={styles.text}>
              Rock Island Police Department
              {'\n'}
              309- 732-2677
            </Text>
          </Button>
            </Col>
            <Col style={styles.rightContent}>
            <Button style={styles.textBlock}>
            <Text style={styles.text}>
              National Suicide Prevention Line {'\n'}
              800-273-8255
            </Text>
          </Button>
          <Button style={styles.textBlock}>
            <Text style={styles.text}>
              Poison Control Center  {'\n'}
              800-222-1222
            </Text>
          </Button>
          <Button style={styles.textBlock}>
            <Text style={styles.text}>
              Dean Of Students{'\n'}
              309-794-7533{'\n'}

            </Text>
          </Button>
            </Col>
          </Grid>
       
        </Content>
      </Container>
