### ISSUE TITLE
Can't update walker's location without erasing everything else about the walker

### ISSUE THREAD

**Issue by chitheprincess** [AugustanaCSC490Spring2021/sandpiper-repo#30]
Walker's location can only be posted to the firebase by the "set" method, as "update" stops the call back function somehow

**Comment by dzwiener** [comment]
Need more info, what have you tried and what errors do you get?

**Comment by chitheprincess** [comment]
I added a feature that gets walkers' location while they're moving and update it to firebase. It has a "callback" part that keeps calling itself after a certain period. I can't use firebase's update method since it stops my get location method somehow, but I can use firebase's set and it works fine. But bc I had to use set, everything else about the walker got erased.

**Comment by dzwiener** [comment]
We changed this to update and it now works.
