### ISSUE TITLE
Create the Resource page

### ISSUE THREAD

**Issue by dzwiener** [AugustanaCSC490Spring2021/sandpiper-repo#4]
Create the resource page as laid out in the storyboard. This should also include linking the button from the home page to the Resource page so that the button functions as it should. Also include the back button on the resource page.

**Comment by mwardach** [comment]
I assigned this as it is related to creating a list of documents for this page. Rather than creating it, I'll be adding to the resource page as I find more resources.

**Comment by dzwiener** [comment]
I was thinking adding each resource we will be using to a total list might be helpful for documentation purposes. But if you think it'll be easier to skip that step and implement it app side, your call.

**Comment by mwardach** [comment]
Sorry, I was still planning to have a master list of our documentation, but I was planning to implement some of the resources in the app for the first sprint to display. Sorry if that was unclear.

**Comment by dzwiener** [comment]
Oh ok, sure if you want to implement that. We will need a web view or some way to display the information.

**Comment by mwardach** [comment]
Resources page created. The rest of this issue is contained in creating the list of documentation for resources
